### ISSUE TITLE
import pyvw - seg faults

### ISSUE THREAD

**Issue by simonhughes22** [JohnLangford/vowpal_wabbit#760]
Running  Mac OSX 10.10.5, just downloaded the source, then brew installed boost, libtools, automake, etc. Running 
```shell
make
make tests 
```
Test #16 fails. Ignoring that I ran 

``` shell
make install
cd ./python
make
```
Then I got this printed out:
``` shell
cd ..; /Applications/Xcode.app/Contents/Developer/usr/bin/make python
cd vowpalwabbit; /Applications/Xcode.app/Contents/Developer/usr/bin/make -j 8 things
make[2]: Nothing to be done for `things'.
cd python; /Applications/Xcode.app/Contents/Developer/usr/bin/make things
/usr/bin/g++ -std=c++0x -I/Users/simon.hughes/anaconda/include/python2.7 -I/Users/simon.hughes/anaconda/include/python2.7 -I /opt/local/include -fPIC -c pylibvw.cc -o pylibvw.o
/usr/bin/g++ -shared  pylibvw.o -L /opt/local/lib -lpython2.7 -ldl -framework CoreFoundation -u _PyMac_Error ../vowpalwabbit/libvw.a ../vowpalwabbit/liballreduce.a -L /opt/local/lib -lboost_program_options-mt -lboost_serialization-mt -l pthread -l z -l boost_python -o pylibvw.so
```
If I then launch python, and do
`import pyvw`
I get
``` shell
/Users/simon.hughes/anaconda/bin/python.app: line 3: 60336 Segmentation fault: 11  /Users/simon.hughes/anaconda/python.app/Contents/MacOS/python "$@"
```

**Comment by JohnLangford** [comment]
Hal, can you look into this?

-John

**Comment by JohnLangford** [comment]
Test #16 has been fixed.   What is the status of python on Mac?

**Comment by mengdong** [comment]
problem still exist

**Comment by jharaldson** [comment]
Seems this issue remains. Any ideas of how to progress with this? Would be nice to be able to interface vowpal wabbit a Mac OS.

**Comment by amrsharaf** [comment]
@jharaldson check my follow-up comments here: https://github.com/JohnLangford/vowpal_wabbit/issues/415

Hopefully this will help you compiling the python interface on Mac OS X.

**Comment by jharaldson** [comment]
Using the homebrew path for python works as suggested.

**Comment by JohnLangford** [comment]
Closing, appears resolved.
