### ISSUE TITLE
Assertion failure in Java interface predict

### ISSUE THREAD

**Issue by marko-asplund** [JohnLangford/vowpal_wabbit#800]
A program using VW Java interface dies of `SIGABRT` in `Java_vw_VW_predict` when VW is built with assertions enabled. The occurs because an assertion fails in

```VW::finish_example(*vwInstance, vec2);```

Here's the error message I get:
```java: parser.cc:996: void VW::finish_example(vw&, example*): Assertion `ec->in_use' failed.```

It seems that the `in_use` flag gets cleared in

```
vwInstance->l->predict(*vec2);
```

**Comment by JohnLangford** [comment]
I'm not understanding the in_use bug.  Generally predict() does not clear the in_use flag.  The only line that can clear the in_use flag in normal use is here:

https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/parser.cc#L996

This is inside a lock, so this is a very sensitive variable.

**Comment by marko-asplund** [comment]
I can reproduce this issue like this:

```
git clone https://github.com/marko-asplund/vowpal_wabbit
cd vowpal_wabbit
git checkout jni-topic-predictions
sed -i.tmp '74,74 s/^#//' Makefile
cd java
make
mvn test
```

**Comment by JohnLangford** [comment]
This is fixed now, correct?

-John

**Comment by marko-asplund** [comment]
I think it's not fixed. With the latest Java interface multiprediction changes from PR #809 I can reproduce the issue like this:
```
git clone https://github.com/jmorra/vowpal_wabbit
cd vowpal_wabbit
git checkout 75fe0db
sed -i.tmp '74,74 s/^#//' Makefile
cd java
make
mvn test
```

**Comment by jmorra** [comment]
This appears to still be happening in the latest build.

**Comment by JohnLangford** [comment]
@jmorra Any idea what's up?  I'd like to do a release today and this is a bit worrisome.

**Comment by jmorra** [comment]
We just got a report of a memory leak in the current implementation of the
JNI interface. Can we hold off on the release until this is diagnosed? Ryan
is working on verifying it today.

As for this issue, I have no idea, this seems like it's on the C side.

**Comment by JohnLangford** [comment]
It might be related to this.  The library interface should not have this
problem (and does not in other libraries).  Something is off.

-John

**Comment by jmorra** [comment]
Yea, I'm just not sure what to do. Is there something that I'm doing
improperly in the templated shared function? I don't know where else to
look.

**Comment by jmorra** [comment]
Debugging this further, it appears to only happen during the LDA test.  It specifically happens on the line where we call `learn` on some text data after creating a model with the following parameters `--quiet -b 4 --lda 3 -f %s --readable_model %s`.  @JohnLangford does this help isolate the issue?  All the other tests work fine.

**Comment by jmorra** [comment]
I've noticed that in `lda_core.cc` `finish_example` is an empty method and `VW::finish_example` is never called.  @JohnLangford does that example what's going on?

**Comment by jmorra** [comment]
@JohnLangford I have an update that fixes this by simply not calling `VW::finishExample` for the `VWFloatArrayLearner`.  I don't want to make a pull request yet because I want to hear from you whether or not that's a good idea.

**Comment by JohnLangford** [comment]
There's something difficult here.

The problem is that lda is a minibatch algorithm which means that it 
uses multiple examples at once.  This is required because of the 
variational approximation which happens in the update rule.

Hence finish_example() is a noop, and the finishing of examples is 
handled in line 684 or 752.  Predict has the same structure, except that 
you are defaulting to a minibatch of size 1.

Hence, yes, you do not want to call VW::finishExample since it is 
already called.  But this is _not_ specific to the prediction 
type---instead it's specific to the batch algorithm.  So, we want 
something like: if (!all.lda) VW::finishExample.   That's kind-of 
yucky.  Any suggestions for alternatives?

-John

**Comment by jmorra** [comment]
Looking at the code it looks like the `lda` code already called `VW::finishExample` hence I think your suggestion makes sense.  I can't think of another way of accomplishing this.  BTW this is definitely not related to the memory leak reported by the eH guys because eH isn't using LDA here.
