### ISSUE TITLE
Model is not saved when --passes exceeds 2

### ISSUE THREAD

**Issue by kirillfish** [JohnLangford/vowpal_wabbit#859]
Recently I asked a question [here](http://stackoverflow.com/questions/33800919/vowpal-wabbit-doesnt-save-the-model-despite-f-flag-is-present) on StackOverflow.

Actually, there appeared to be a much more minimalistic way to describe the problem. Here is the training set:

-1 |D a
1 |D b
-1 |D a
-1 |D c
1 |D d
-1 |D a
1 |D b
1 |D a
-1 |D d

After running this command:
`vw toy_example -f heythere.model -c --loss_function logistic --passes 3`
no model is saved, as well as for greater --passes values. 

But these commands:
`vw toy_example -f heythere.model -c --loss_function logistic --passes 2`
`vw toy_example -f heythere.model -c --loss_function logistic --passes 1`
both work as expected.

**Comment by arielf** [comment]
I can 100% reproduce this.
`--loss_function logistic` isn't necessary to reproduce.

The bug has been there for a long time (I went back to 2013 and it is still there)

It seems to be related to holdout and hold-out period.

The bug disappears if any of the following hold true:
    * Add `--holdout_off` to the options, no hold-out, no issues.
    * Increase passes to 10 or more (strangely: 2 passes work byt 3 to 9 don't, 10 passes work again)
   * Add more examples: 10 or more examples make it work again

 Here's a script that can easily show the bug
```
$ cat 3pass-no-model-save.sh
#!/bin/bash
#
# https://github.com/JohnLangford/vowpal_wabbit/issues/859
# -f model - model doesn't get saved with 3-9 passes
#
# Broken:
# VW=~/bin/vw-8.20151121
# VW=~/bin/vw-8.20151101
# VW=~/bin/vw-8.20151019
# VW=~/bin/vw-8.20151013
# VW=~/bin/vw-8.20151005
# VW=~/bin/vw-8.20151002
# VW=~/bin/vw-8.20150927
# VW=~/bin/vw-8.20150902
# VW=~/bin/vw-7.20150623
# VW=~/bin/vw-7.20150609
# VW=~/bin/vw-7.20150608
# VW=~/bin/vw-7.20150527
# VW=~/bin/vw-7.20140824

VW=`which vw`

MyName=`basename -s .sh $0`

TrainSet="$MyName.train"
Model="$MyName.model"

test_it() {
    passes=$1

    pass_opt=""
    case "$1" in
        ([2-9]) pass_opt="-c --passes $1" ;;
    esac

    rm -f $Model
    $VW -k --quiet $pass_opt --loss_function logistic -d $TrainSet -f $Model

    if [ -s $Model ]; then
        # exists and has non-zero size
        echo "=== OK:    passes $1  seems to work"
        # ls -l $Model
    else
        echo "=== ERROR: passes $1  produced no model"
    fi
}

cat > $TrainSet <<'EOF'
-1 |D a
1 |D b
-1 |D a
-1 |D c
1 |D d
-1 |D a
1 |D b
1 |D a
-1 |D e
EOF

for i in '' 2 3 4 5 6 7 8 9 10 11 12 13 20; do
    test_it $i
done
```

**Comment by kirillfish** [comment]
@arielf: thank you for quick reply! But in fact, at least on my machine, the bug affects not only tiny datasets, but also real ones with millions of examples! That was the initial reason for my SO question: when consecutively training different `vw` models (with different hyperparameter configurations) on my real dataset (about 25M observations), the model is not saved when --passes>2. `toy_example` is just the contrived minimal example for your convenience.

**Comment by kirillfish** [comment]
I started with my initial dataset and was reducing it's volume and pruning away features and namespaces until it came down to `toy_example`. So I inferred that input file doesn't cause the problem. Then I experimented with different flags, and it seems that only --passes>2 entails this behavior (I'm not sure about >10).

**Comment by JohnLangford** [comment]
This seems like a real head-scratcher.

-John

**Comment by arielf** [comment]
@kirillfish can you reproduce on a big data-set with `-k` option (delete cache before starting) ?

**Comment by kirillfish** [comment]
@arielf the bug is reproduced when `-k` is used.

**Comment by kirillfish** [comment]
By the way, I noticed interesting behavior of `vw`. On my big data set `vw` also doesn't report that it used multiple passes (i.e., there is no string like `passes used = 3` in diagnostic output). On top of this, the letter `h` is not printed at the end of lines corresponding to repeated epochs (but as I understand, it should, because with no `--holdout_off` flag it should report holdout error on repeated epochs). This occurs regardless of whether the model is saved in the end.

**Comment by kirillfish** [comment]
The problem is also reproduced with other datasets of the same type that I can obtain. Here is a sample string from the dataset, just in case:

`-1 |D lorsovet.info |R \N |S 0 |C 7644 |T 2015-10-12-00-02-02 |Z 160x600 |E between |L 4514 |M 1126 |P 33662 |I 18394 |A 716 |U Yandex-Browser-15.6.2311 Android_5.0.1 |O 71e7f4db-7e35-fbbe-36e3-ee34f74fbde3 |N RU |Y \N |W MON |P NIGHT |{ recency:7.3898 frequency:1`

**Comment by JohnLangford** [comment]
This is fixed in the current master, at least for toy_example.   The core
issue was holdout not being handled properly when there were no holdout
examples.  Please check on your larger dataset.

@arielf, thanks for your help.

-John

**Comment by arielf** [comment]
Thanks John

Confirming that latest master fixes the issue for 3-9 passes on the toy (9 examples) data set.
Also tried a few bigger data sets and wasn't able to reproduce.

**Comment by kirillfish** [comment]
Thank you @JohnLangford @arielf! Maybe my problem is system-specific. I cloned the latest master and reinstalled Vowpal Wabbit, but the problem is still present :disappointed: 

@arielf did you tried multiple passes with `--ftrl`? I noticed that using `--ftrl` leads to not saving the model on my data, while default algorithm for some reason saves it.

Nevertheless, as @arielf pointed out, if I simply specify `--holdout_off`, the model is always saved. Maybe I can dispense with holdout: it would be even more essential not to use early stopping if I treat `--passes` as a hyperparameter to optimize.

**Comment by arielf** [comment]
@kirillfish   thanks for the `--ftrl` detail.
I just used my script above (no `--ftrl` to reproduce and test)
When I add `--ftrl` to the options, I can reproduce the bug again, so my guess is that the fix John applied (which was good) just needs to be applied in another place in the code where `--ftrl` is in effect and possibly in other reductions.

**Comment by JohnLangford** [comment]
What is an example exhibiting the revised bug?

**Comment by JohnLangford** [comment]
Got it.  Pushed a fix for --ftrl.

-John

**Comment by kirillfish** [comment]
Thank you! Now my models are saved with `--ftrl` as well.
