### ISSUE TITLE
Cannot extract the weights from a matrix factorization model

### ISSUE THREAD

**Issue by jfk178** [JohnLangford/vowpal_wabbit#933]
I cloned and installed VW from the master branch and tried to extract the weights from a matrix factorization model. As explained in the tutorial, I did:

```
echo '|u 42 |i 7' | ./gd_mf_weights -I /dev/stdin --vwparams '-q ui --rank 10'
```

The matrix weights are stored in two files:

```
$ cat u.quadratic
42      0.03819522  0.01859808  0.05079339  0.09795442  0.01577788 \
0.03559553  0.03511773  0.06763012  0.07147525  0.01441927

$ cat i.quadratic
7       0.001774097 0.09892741  0.0003603621    0.08734247  0.031095 \
0.04543924  0.08084627  0.05934385  0.031871    0.02616241
```

However I want to use the trained model stored in model.reg. So I did the following:

```
echo '|u 42 |i 7' | ./gd_mf_weights -I /dev/stdin --vwparams '-i model.reg'
```

This time, the same files are empty:

```
$ cat u.quadratic
42

$ cat i.quadratic
7
```

I compiled VW from the master branch on Ubuntu 14.04 , Debian 8.0 and Mac OS X. Each time the files u.quadratic and i.quadratic were empty.

**Comment by JohnLangford** [comment]
Not sure what's up.  Jake?

-John

**Comment by JohnLangford** [comment]
i'm not sure what's up here, since i haven't used the gd_mf_weights code in
quite a while, and there have been significant changes to the VW codebase
since then.

i'll take a look and discuss with john to debug.

**Comment by JohnLangford** [comment]
@jhofman have you had a chance to look?

**Comment by JohnLangford** [comment]
@jhofman ping

**Comment by JohnLangford** [comment]
I believe this is fixed in the current master.

**Comment by bendrecm** [comment]
Still facing this issue. Running this command 
`echo '|u 42 |i 7' | ./gd_mf_weights -I /dev/stdin --vwparams '-i model.reg'`

prints empty output on disk in i.quadratic and u.quadratic files.

**Comment by jhofman** [comment]
@bendrecm: looks like you were missing '-q ui' in the vwparams.

I've updated the [wiki page](https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Matrix-factorization-example) to clarify. I just tested the MovieLens example there and it appears to be working fine.
